---
title: "7. Conclusions"
author: "B233241"
date: "2025-01-07"
output:
  pdf_document:
    latex_engine: xelatex
    dev: cairo_pdf
knit: (function(inputFile, encoding) {
      rmarkdown::render(inputFile,
                        encoding = encoding,
                        knit_root_dir = rprojroot::find_rstudio_root_file(),
                        output_dir = file.path("../Output")
                        )})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Word count: `r wordcountaddin::word_count(here::here("MSc_Thesis_Split", "Script", "_7_Conclusions.Rmd"))`

# Conclusions

This project principally aimed to establish whether the \acr{WME} causal effect estimation method for \acr{MR} studies produces over-confident effect estimates versus the MR-Hevo method, and whether this might affect the validity of conclusions drawn in real-world studies. 

Using simulated data with known parameters, \acr{WME} and MR-Hevo produced similar effect estimates and 95% \acr{CI}s when averaged over all cases.  However, MR-Hevo reported wider \acr{CI}s than \acr{WME} specifically in cases where key assumptions of \acr{IV} analysis were relatively more violated; this resulted in an overall false-positive report rate an order of magnitude lower for MR-Hevo versus \acr{WME} (`r no_causal_Hevo_mean_pos_rate`% versus `r no_causal_WME_mean_pos_rate`%) across simulations with no causal effect present. In cases where a causal effect truly was present, the overall sensitivity was slightly higher for MR-Hevo versus \acr{WME} (`r causal_Hevo_mean_pos_rate`% versus `r causal_WME_mean_pos_rate`%), though this appeared to be driven by one parameter combination in particular (20,000 simulated participants, 0% invalid instruments), an observation which warrants further explanation before accepting this conclusion. In a majority of cases (58%), MR-Hevo's greatly improved specificity came at the expense of a moderate drop in sensitivity, typically in the order of 5-10%, though up to 23% in the most extreme case. Higher sensitivities with \acr{WME} versus MR-Hevo analysis appeared to correlate with increasing effect of parameters and assumption violations biasing away from the null; this result may therefore represent MR-Hevo estimates being more robust to assumption violations than those of \acr{WME}.

Re-analysis of data from highly cited \acr{MR} studies was attempted. \acr{WME} causal effect estimates were found to be poorly reproducible\acr{WME} from available data; this finding alone is concerning for the validity of conclusions for the whole field of \acr{MR}, though further investigation of this phenomenon was outside the scope of this project. MR-Hevo produced 95% \acr{CI}s that were wider on average than those generated by \acr{WME}, and in 6 of 10 cases this difference was large enough that it could plausibly have changed conclusions for a small causal effect size. In the sample of 10 re-analysed studies, the final conclusion regarding prescence of a true causal effect was not changed in any case by use of MR-Hevo versus \acr{WME} methods. Characteristics of included studies were noted to diverge significantly from simulation parameters used in the original validation of \acr{WME} and reproduced in this project, particularly in terms of number of participants and number of genetic instruments used.

These results suggest that MR-Hevo may be a more suitable method than \acr{WME} for avoiding false-positive reports of causality between exposures and outcomes, which has been a key challenge for the field of \acr{MR} of late. Within the limitations of the small sample of relatively high-quality \acr{MR} studies re-analysed, it does not appear necessary to disregard all conclusions drawn from existing \acr{WME} \acr{MR} analyses. Given the tendency of \acr{WME} to produce false-positive results, re-analysis of \acr{MR} studies reporting causality using \acr{WME} may be warranted in some selected cases, particularly where results are borderline, where \acr{IV} analysis assumptions are likely to be substantially violated, or where significant further action is planned on the basis of \acr{MR} results. The main drawbacks of MR-Hevo versus \acr{WME} are a reduction in sensitivity, and a more computationally intensive implementation. Suggested directions for future work include quantifying and further characterising the non-reproducibility of \acr{MR} results observed here, and evaluating \acr{MR} causal estimation methods using simulation parameters representative of observed values from existing real-world studies.

\newpage